From slt.kit-server

#PyTorch
RUN apt-get install -y libyaml-dev && \
    pip install http://download.pytorch.org/whl/cpu/torch-0.3.1-cp27-cp27mu-linux_x86_64.whl && \
    pip install "torchvision<0.3" && \
    pip install -U numpy && \
    pip install -U nltk

#OPENNMT
RUN mkdir -p /opt/lib && \
    cd /opt/lib && \
    git clone https://github.com/quanpn90/OpenNMT-py

CMD /opt/SLT.KIT/src/server/RUN.sh